name: Shorebird Patch

on:
  push:
    branches:
      - main
      - master # Included in case your default branch is named master

jobs:
  patch:
    name: Build & Publish Patch
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: 📦 Shorebird Patch Android
        run: shorebird patch android --allow-asset-diffs
        env:
          # This token is required for CI/CD to authenticate with Shorebird
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
